### ISSUE TITLE
GUI showing wrong interface mappings

### ISSUE THREAD

**Issue by panks21** [Juniper/wistar#2]
After creating the topology on the GUI, it is observed that it does not show the interface mapping correctly. For example vmx1 -- vmx2 interface is being shown as vmx1 -- vmx3. 
Attachment shows the wrong mapping. The correct is as shown in the CLI below

root@vmxa_1# show interfaces 
ge-0/0/0 {
    description "To vmxa_2";
    unit 0 {
        family inet {
            address 172.16.0.21/30;
        }
    }
}
ge-0/0/1 {
    description "To vmxa_3";
    unit 0 {
        family inet {
            address 172.16.0.25/30;
        }
    }
}
ge-0/0/2 {
    description "To A-LR-mx104";
    flexible-vlan-tagging;
    encapsulation flexible-ethernet-services;
    unit 101 {
        vlan-id 101;
        family inet {
            address 172.16.0.13/30;     
        }
    }
}
fxp0 {
    unit 0 {
        family inet {
            address 192.168.122.2/24;
        }
    }
}
![wistar1](https://cloud.githubusercontent.com/assets/18426368/21527546/03e99728-cd52-11e6-972c-5a9e7a773117.JPG)

**Comment by nembery** [comment]
found a an issue with GUI library. I've implemented a fix, but it requires some testing and validation first. Please test the latest commit and let me know how this works for you.

**Comment by panks21** [comment]
It got fixed partially but few routers still showing wrong mappings.... :(
